config/routes.rb
Opinio::Application.routes.draw do
  resources :polls

   match 'polls/:id/create_answer' => 'polls#create_answer'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :affirmative
  belongs_to :poll
end

app/models/number.rb
class Number < ActiveRecord::Base
  attr_accessible :number
  has_many :answers
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @polls }
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])

    #@yes_percentage = trues / @poll.answers.count.to_f
    #@username = @answer.number.last(4)

    trues = 0
    falses = 0
    @poll.answers.each do |a| 
      if a.affirmative == true
        trues = trues + 1
      else
        falses = falses + 1
      end
    end

    @yes_percentage = trues / @poll.answers.count.to_f
    @trues = trues
    @falses = falses
    @total = @poll.answers.count

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/new
  # GET /polls/new.json
  def new
    @poll = Poll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/1/edit
  def edit
    @poll = Poll.find(params[:id])
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(params[:poll])

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render json: @poll, status: :created, location: @poll }
      else
        format.html { render action: "new" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create_answer
    @answer = Answer.new
    logger.debug @answer
    return if params[:From].blank?
    if params[:Body] == true || params[:Body] =~ (/(true|True|TRUE|t|yes|Yes|YES|y|Y|1)$/i)
      @answer.affirmative = true
    elsif params[:Body] == false || params[:Body] =~ (/(false|False|FALSE|f|no|No|NO|n|N|0)$/i) 
      @answer.affirmative = false   
    end 
    @answer.number = params[:From]
    @poll = Poll.find(params[:id])
    @poll.answers << @answer
    @answer.save
    @poll.save

    #trues = @poll.answers.inject(0) { |sum, n| sum + (n ? 1 : 0) }
    trues = 0
    falses = 0
    @poll.answers.each do |a|
      if a.affirmative == true
        trues = trues + 1
      end
      if a.affirmative == false
        falses = falses + 1
      end
    end

    logger.debug yes_percentage = trues / @poll.answers.count.to_f
    logger.debug username = @answer.number.last(4)
    logger.debug @answer.affirmative

    Pusher['opinio'].trigger!('action_created', {:some => 'data', :vote => @answer.affirmative, :username => username, :trues => trues, :falses => falses, :yes_percentage => yes_percentage})
	@pusher_live = true
    respond_to do |format|
      format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
      format.json { render json: @poll }
    end
  end

  # PUT /polls/1
  # PUT /polls/1.json
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<%= yield %>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @polls.each do |poll| %>
  <tr>
    <td><%= poll.name %></td>
    <td><%= poll.description %></td>
    <td><%= link_to 'Show', poll %></td>
    <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
    <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Poll Result - OPINIO</title>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" href="../../css/normalize.css">
    <link rel="stylesheet" href="../../css/main.css">
    <script src="../../js/vendor/modernizr-2.6.1.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.8.0.min.js"><\/script>')</script>
    <script src="http://js.pusher.com/1.12/pusher.min.js"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <script>
      /* In-Field Label jQuery Plugin
       * http://fuelyourcoding.com/scripts/infield.html
       *
       * Copyright (c) 2009 Doug Neiner
       * Dual licensed under the MIT and GPL licenses.
       * Uses the same license as jQuery, see:
       * http://docs.jquery.com/License
       *
       * @version 0.1
       */(function(a){a.InFieldLabels=function(b,c,d){var e=this;e.$label=a(b);e.label=b;e.$field=a(c);e.field=c;e.$label.data("InFieldLabels",e);e.showing=!0;e.init=function(){e.options=a.extend({},a.InFieldLabels.defaultOptions,d);if(e.$field.val()!=""){e.$label.hide();e.showing=!1}e.$field.focus(function(){e.fadeOnFocus()}).blur(function(){e.checkForEmpty(!0)}).bind("keydown.infieldlabel",function(a){e.hideOnChange(a)}).change(function(a){e.checkForEmpty()}).bind("onPropertyChange",function(){e.checkForEmpty()})};e.fadeOnFocus=function(){e.showing&&e.setOpacity(e.options.fadeOpacity)};e.setOpacity=function(a){e.$label.stop().animate({opacity:a},e.options.fadeDuration);e.showing=a>0};e.checkForEmpty=function(a){if(e.$field.val()==""){e.prepForShow();e.setOpacity(a?1:e.options.fadeOpacity)}else e.setOpacity(0)};e.prepForShow=function(a){if(!e.showing){e.$label.css({opacity:0}).show();e.$field.bind("keydown.infieldlabel",function(a){e.hideOnChange(a)})}};e.hideOnChange=function(a){if(a.keyCode==16||a.keyCode==9)return;if(e.showing){e.$label.hide();e.showing=!1}e.$field.unbind("keydown.infieldlabel")};e.init()};a.InFieldLabels.defaultOptions={fadeOpacity:.5,fadeDuration:300};a.fn.inFieldLabels=function(b){return this.each(function(){var c=a(this).attr("for");if(!c)return;var d=a("input#"+c+"[type='text'],"+"input#"+c+"[type='password'],"+"textarea#"+c);if(d.length==0)return;new a.InFieldLabels(this,d[0],b)})}})(jQuery);$(function(){$("label").inFieldLabels()});

      var Data = {
        yes_percentage: <%= @yes_percentage %>,
        trues: <%= @trues %>,
        falses: <%= @falses %>,
        total: <%= @total %>
      };

      // There must be a flag for this?
      <% if false %>
      // Enable pusher logging - don't include this in production
      Pusher.log = function(message) {
        if (window.console && window.console.log) window.console.log(message);
      };

      // Flash fallback logging - don't include this in production
      WEB_SOCKET_DEBUG = true;
      <% end %>

      // Update the chart.
      var called = false;
      var update = function update(Data) {
        $('#left-count').animate({
          width: (1 - Data.yes_percentage) * 100 + '%'
        }, 5000, function() { /* Animation complete. */ });
        $('#no-count span').text(Data.falses);
        $('#yes-count span').text(Data.trues);
        $('#left-percentage').text(Math.round(100 * (1 - Data.yes_percentage)) + '%');
        $('#right-percentage').text(Math.round(100 * Data.yes_percentage) + '%');
			if(Boolean(Data.vote)===true){$('.yes').effect("bounce", { times:5 }, 1000);}
			if(Boolean(Data.vote)===false){$('.no').effect("bounce", { times:5 }, 1000);}
        if (called)
          $('#live-vote-output').fadeIn(150, function() {
            $(this).find('span').text(Data.username);
          }).delay(500).fadeOut(150);
        else called = true;
      }

      var pusher = new Pusher('af559ff310637b1d44a8');
      var channel = pusher.subscribe('opinio');
      channel.bind('action_created', function(data) {
        // This is weird and should be fixed next.
        if (data.yes_percentage) {Data.yes_percentage = data.yes_percentage;}
        Data.vote = data.vote;
        if (data.username) {Data.username = data.username;}
        if (data.trues) {Data.trues = data.trues;}
        if (data.falses) {Data.falses = data.falses;}
        if (data.total) {Data.total = data.total;}

        // Update the graph when Pusher pushes.
        update(Data);
      });

      // Update the graph when the page loads.
      $(function() { update(Data); });
    </script>
    </head>
    <body>
      <header>
        <div class="wrap">
          <h1>OPINIO</h1>
          <h2>Simple text message based polling.</h2>
          <ul id="logo-icons">
            <li><i class="icon-phone"></i></li>
            <li class="omega"><i class="icon-ok"></i></li>
          </ul>
        </div>
      </header>
      <div id="main">
        <div class="wrap">
          <h1 id="question-title">Would you like to receive Cat Facts?</h1>
          <p id="answer-options">Text <span class="blue">yes</span> or <span class="red">no</span> to <strong>(512) 271-4310</strong> to vote.</p>
        </div>
        <div id="slider-container">
        <div id="left">
          <div id="left-sider"></div>
          <div class="bend" id="red"></div>
        </div>
        <div id="mid">
          <div class="count" id="left-count"><h4 id="left-percentage"></h4></div>
          <div class="count" id="right-count"><h4 id="right-percentage"></h4></div>
        </div>
        <div id="right">
          <div id="right-sider"></div>
          <div class="bend" id="blue"></div>
        </div>
      </div>
      <div id="lower-data" class="wrap">
        <div class="count-output" id="left-count-container">
          <h3 class="no">NO</h3>
          <p id="no-count"><span>0</span> votes</p>
        </div>
        <div id="live-vote-output">
          Vote submitted<br/>
          (###) ###-<span></span>
        </div>
        <div class="count-output" id="right-count-contaier">
          <h3 class="yes">YES</h3>
          <p id="yes-count"><span>0</span> votes</p>
        </div>
      </div>
      <br style="clear: both"/>
    </div>
    <script src="/js/main.js"></script>
    </body>
</html>